name: sprawozdanie
on: push

jobs: 
  pdf:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y texlive-xetex pandoc inkscape
      - run: sudo apt-get install -y texlive-fonts-recommended texlive-plain-generic
      
      - run: pip install ipykernel scipy pint open_atmos_jupyter_utils matplotlib nbconvert pympdata
      - uses: actions/checkout@v4
      
      - run: python -m nbconvert --to latex --execute projekt1/projekt_plytka_woda_Slotwinski.ipynb --output-dir . --output projekt_Slotwinski
  
      - run: sed -i '/\\maketitle/d' projekt_Slotwinski.tex
      - run: |
          xelatex -interaction=nonstopmode projekt_Slotwinski.tex
          xelatex -interaction=nonstopmode projekt_Slotwinski.tex
      
      - uses: actions/upload-artifact@v4
        with:
          path: projekt_Slotwinski.pdf